name: MindScraper
description: Blogging about stuffs
meta_description: "Nicolas joseph's blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'nicolasjoseph.com'
google_analytics: 'UA-1842340-4'

# Details for the RSS feed generator
url:            'http://www.nicolasjoseph.com'
author:         'Nicolas Joseph'
